# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 091566b0ecc1ca825e4f3a4a714f2724a985721eedc067783b769c63ffde403ac97a252c021d913f6a17525f9847f53d1ca79ddba3964247360261b8cad38c13

test:
  secret_key_base: c60acb5eeaf3836634c43203bdd8d46537c511238e2c7a1951e9c7a8c3aadd6f0280c8977f28790e3e0cb9632be95a3971ece1c7d81eb3fdd8f395a12d556432

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
